version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: eduforge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_schemas.sql:/docker-entrypoint-initdb.d/init.sql

  identity:
    build: ./identity
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./identity:/app

volumes:
  pgdata:
